{application,mix_test_watch,
             [{description,"Automatically run tests when files change"},
              {modules,['Elixir.Mix.Tasks.Test.Watch','Elixir.MixTestWatch',
                        'Elixir.MixTestWatch.CompileTask',
                        'Elixir.MixTestWatch.Config',
                        'Elixir.MixTestWatch.GenTask',
                        'Elixir.MixTestWatch.HotRunner',
                        'Elixir.MixTestWatch.MessageInbox',
                        'Elixir.MixTestWatch.Path',
                        'Elixir.MixTestWatch.PortRunner',
                        'Elixir.MixTestWatch.Runner',
                        'Elixir.MixTestWatch.TestTask',
                        'Elixir.MixTestWatch.Watcher']},
              {registered,[]},
              {vsn,"0.3.3"},
              {mod,{'Elixir.MixTestWatch',[]}},
              {applications,[kernel,stdlib,elixir,fs]}]}.
