export const AUTH_TOKEN_KEY = 'AUTH_TOKEN_KEY'

export const CHANGE_FORM = 'AUTH_CHANGE_FORM'
export const LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const ON_LOGIN_SUCCESS = 'AUTH_ON_LOGIN_SUCCESS'
export const ON_LOGIN_ERROR = 'AUTH_ON_LOGIN_ERROR'

export const ON_LOGOUT_SUCCESS = 'ON_LOGOUT_SUCCESS'

export default {
  CHANGE_FORM,
  LOGIN_REQUEST,
  ON_LOGIN_SUCCESS,
  ON_LOGIN_ERROR,
  AUTH_TOKEN_KEY,
  ON_LOGOUT_SUCCESS,
}