{application,mix_docker,
             [{description,"Put your Elixir app production release inside minimal docker image"},
              {modules,['Elixir.Mix.Tasks.Docker.Build',
                        'Elixir.Mix.Tasks.Docker.Customize',
                        'Elixir.Mix.Tasks.Docker.Init',
                        'Elixir.Mix.Tasks.Docker.Publish',
                        'Elixir.Mix.Tasks.Docker.Release',
                        'Elixir.Mix.Tasks.Docker.Shipit','Elixir.MixDocker']},
              {registered,[]},
              {vsn,"0.4.2"},
              {applications,[kernel,stdlib,elixir,logger]}]}.
